# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: survey-empire_development
  pool: 5
  username: postgres
  password: password
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: survey-empire_test
  pool: 5
  username: postgres
  password: password
  timeout: 5000